title:              The Smart Robot
email:              <firstname>.<name>@ugent.be
description:        Crucially, reading this blog will reduce your Free Energy.
author:             Tim Verbelen, Ozan Catal, Toon Van de Maele
baseurl:            ""
url:                "https://thesmartrobot.github.io"


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-5683118-8

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
